version: '3.1'

services:
  db:
    image: mongo:7
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=1234567890
    #   - MONGO_INITDB_DATABASE=hakaton
