version: '3.9'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - '5001:5001'
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${NAMEDB}
      POSTGRES_USER: ${DBLOGIN}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
volumes:
  docker-nest-postgres:
