name: Hakaton e-commerce
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Staring Node js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules client
        run: cd client && npm install
      - name: build project client
        run: cd client && npm run build
      - name: lint code client
        run: cd client && npm run lint:fix
      - name: check types back
        run: cd server && npm run types
